#!/bin/bash

args=("${@}") && [ -n "${args}" ] || args=("${PWD}")

# this is non-destructive. if no emblems are found we simply move on, instead of removing any existing backups.
find "${args[@]}" -type d | while read dir; do
    icon=$(gio info -na metadata::custom-icon "$(realpath "${dir}")" | awk 'match($0, "metadata::custom-icon: (.+)",m) { print m[1] }' | sed 's/,/ /g')
    [ -n "${icon}" ] && echo "${icon}" > "${dir}/.custom-icon~"
    emblems=$(gio info -na metadata::emblems "$(realpath "${dir}")" | awk 'match($0, "metadata::emblems: \\[(.+)\\]",m) { print m[1] }' | sed 's/,/ /g')
    [ -n "${emblems}" ] && echo "${emblems}" > "${dir}/.emblems~"
done

