#!/bin/bash

args=("${@}") && [ -n "${args}" ] || args=("${PWD}")

# this is non-destructive. if no emblems are found we simply move on, instead of removing any existing backups.
find "${args[@]}" -type d | while read dir; do
    emblems=$(gio info -na metadata::emblems "$(realpath "${dir}")" | awk 'match($0, "metadata::emblems: \\[(.+)\\]",m) { print m[1] }' | sed 's/,/ /g')
    [ -n "${emblems}" ] && echo "${emblems}" > "${dir}/.emblems~"
done

