#!/bin/bash

[ -n "${1}" ] || exit

for x in "${@}"; do
    gio set -nt unset "$(realpath "${x}")" metadata::custom-icon
    gio set -nt unset "$(realpath "${x}")" metadata::emblems
    # poke inotify (refresh nemo) by touching without changing
    touch -r "${x}" "${x}"
done

